apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k6t382qy7-nodejs
  janus-idp.io/tekton: k6t382qy7-nodejs
  backstage.io/kubernetes-id: k6t382qy7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k6t382qy7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
